/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as DpaRouteImport } from './routes/dpa'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CarreirasRouteImport } from './routes/carreiras'
import { Route as CadastrarRouteImport } from './routes/cadastrar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolucoesMidasRouteImport } from './routes/solucoes.midas'
import { Route as RigsSlugRouteImport } from './routes/rigs.$slug'
import { Route as ModelosSlugRouteImport } from './routes/modelos.$slug'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const DpaRoute = DpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CarreirasRoute = CarreirasRouteImport.update({
  id: '/carreiras',
  path: '/carreiras',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrarRoute = CadastrarRouteImport.update({
  id: '/cadastrar',
  path: '/cadastrar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesMidasRoute = SolucoesMidasRouteImport.update({
  id: '/solucoes/midas',
  path: '/solucoes/midas',
  getParentRoute: () => rootRouteImport,
} as any)
const RigsSlugRoute = RigsSlugRouteImport.update({
  id: '/rigs/$slug',
  path: '/rigs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosSlugRoute = ModelosSlugRouteImport.update({
  id: '/modelos/$slug',
  path: '/modelos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastrar': typeof CadastrarRoute
  '/carreiras': typeof CarreirasRoute
  '/chat': typeof ChatRoute
  '/cookies': typeof CookiesRoute
  '/dpa': typeof DpaRoute
  '/entrar': typeof EntrarRoute
  '/manifesto': typeof ManifestoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/modelos/$slug': typeof ModelosSlugRoute
  '/rigs/$slug': typeof RigsSlugRoute
  '/solucoes/midas': typeof SolucoesMidasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastrar': typeof CadastrarRoute
  '/carreiras': typeof CarreirasRoute
  '/chat': typeof ChatRoute
  '/cookies': typeof CookiesRoute
  '/dpa': typeof DpaRoute
  '/entrar': typeof EntrarRoute
  '/manifesto': typeof ManifestoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/modelos/$slug': typeof ModelosSlugRoute
  '/rigs/$slug': typeof RigsSlugRoute
  '/solucoes/midas': typeof SolucoesMidasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastrar': typeof CadastrarRoute
  '/carreiras': typeof CarreirasRoute
  '/chat': typeof ChatRoute
  '/cookies': typeof CookiesRoute
  '/dpa': typeof DpaRoute
  '/entrar': typeof EntrarRoute
  '/manifesto': typeof ManifestoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/modelos/$slug': typeof ModelosSlugRoute
  '/rigs/$slug': typeof RigsSlugRoute
  '/solucoes/midas': typeof SolucoesMidasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastrar'
    | '/carreiras'
    | '/chat'
    | '/cookies'
    | '/dpa'
    | '/entrar'
    | '/manifesto'
    | '/privacidade'
    | '/termos'
    | '/docs/$slug'
    | '/modelos/$slug'
    | '/rigs/$slug'
    | '/solucoes/midas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastrar'
    | '/carreiras'
    | '/chat'
    | '/cookies'
    | '/dpa'
    | '/entrar'
    | '/manifesto'
    | '/privacidade'
    | '/termos'
    | '/docs/$slug'
    | '/modelos/$slug'
    | '/rigs/$slug'
    | '/solucoes/midas'
  id:
    | '__root__'
    | '/'
    | '/cadastrar'
    | '/carreiras'
    | '/chat'
    | '/cookies'
    | '/dpa'
    | '/entrar'
    | '/manifesto'
    | '/privacidade'
    | '/termos'
    | '/docs/$slug'
    | '/modelos/$slug'
    | '/rigs/$slug'
    | '/solucoes/midas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastrarRoute: typeof CadastrarRoute
  CarreirasRoute: typeof CarreirasRoute
  ChatRoute: typeof ChatRoute
  CookiesRoute: typeof CookiesRoute
  DpaRoute: typeof DpaRoute
  EntrarRoute: typeof EntrarRoute
  ManifestoRoute: typeof ManifestoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  DocsSlugRoute: typeof DocsSlugRoute
  ModelosSlugRoute: typeof ModelosSlugRoute
  RigsSlugRoute: typeof RigsSlugRoute
  SolucoesMidasRoute: typeof SolucoesMidasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpa': {
      id: '/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof DpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carreiras': {
      id: '/carreiras'
      path: '/carreiras'
      fullPath: '/carreiras'
      preLoaderRoute: typeof CarreirasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastrar': {
      id: '/cadastrar'
      path: '/cadastrar'
      fullPath: '/cadastrar'
      preLoaderRoute: typeof CadastrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/midas': {
      id: '/solucoes/midas'
      path: '/solucoes/midas'
      fullPath: '/solucoes/midas'
      preLoaderRoute: typeof SolucoesMidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rigs/$slug': {
      id: '/rigs/$slug'
      path: '/rigs/$slug'
      fullPath: '/rigs/$slug'
      preLoaderRoute: typeof RigsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos/$slug': {
      id: '/modelos/$slug'
      path: '/modelos/$slug'
      fullPath: '/modelos/$slug'
      preLoaderRoute: typeof ModelosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastrarRoute: CadastrarRoute,
  CarreirasRoute: CarreirasRoute,
  ChatRoute: ChatRoute,
  CookiesRoute: CookiesRoute,
  DpaRoute: DpaRoute,
  EntrarRoute: EntrarRoute,
  ManifestoRoute: ManifestoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  DocsSlugRoute: DocsSlugRoute,
  ModelosSlugRoute: ModelosSlugRoute,
  RigsSlugRoute: RigsSlugRoute,
  SolucoesMidasRoute: SolucoesMidasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
